### ISSUE TITLE
Error loading mapillary script

### ISSUE THREAD

**Issue by RobiFag** [3liz/lizmap-javascript-scripts#82]
Hi,
I'm tring to use Mapillary script but when I click on the icon tool I get this error:

```
Composite.js:170 Uncaught TypeError: e.layer.renderDeferred is not a function
    at Composite.js:170:24
    at Array.forEach (<anonymous>)
    at lh.declutter (Composite.js:169:17)
    at lh.renderFrame (Composite.js:143:10)
    at fc.renderFrame_ (Map.js:1570:20)
    at fc.animationDelay_ (Map.js:1424:10)
```

The tool dock appears but the mapillary layer is not loaded. 

I'm using:

- Lizmap 3.7.8
- QGIS Server 3.34.6
- Py-QGIS-Server 1.8.8
- Plugin atlasprint 3.4.0
- Plugin Lizmap server 2.9.2
- Plugin wfsOutputExtension 1.8.0

I get the same error with your demo project too (https://demo.lizmap.com/lizmap/index.php/view/map?repository=javascript&project=mapillary)

![image](https://github.com/user-attachments/assets/510d4ca4-8da2-4df7-b5c4-46973424443a)

**Comment by RobiFag** [comment]
The script works with an old Lizmap installation (3.5.11)

**Comment by nboisteault** [comment]
@RobiFag I have updated the script, can you try it and give us feedback please?

**Comment by RobiFag** [comment]
@nboisteault sorry for the delay, I have just tested the new script and it works! Thanks!
