### PR TITLE
Adding mapillary viewer to Lizmap

### PR DESCRIPTION
**Pull request by Franc-Brs**
HI and thank you for your work, I wrote some times ago a draft script in order to use Mapillay viewer from LM, it can be optimized but at the moment I'm using it in some projects like [this](https://catastostrade.provincia.pc.it/lizmap/lizmap/www/index.php/view/map/?repository=progettipubblici&project=catasto_strade_pub).

### CODE REVIEW

**Comment by nboisteault** [comment]
@Franc-Brs Thank you for your work. I'm making a PR for Mapillary, your work will help me.
It is a WIP : https://github.com/3liz/lizmap-javascript-scripts/pull/55

**Comment by nboisteault** [comment]
@Franc-Brs I have merged my PR. It is based on OL6 and not OL2 as we migrate Lizmap slowly but surely.
Feel free to test it and give us feedback :)

**Comment by Franc-Brs** [comment]
> @Franc-Brs I have merged my PR. It is based on OL6 and not OL2 as we migrate Lizmap slowly but surely and I wanted to use Mapillary vector tiles in browser. Feel free to test it and give us feedback :)

thanks @nboisteault I'll test asap! Nice to know that you used OL6, in fact I had some issues with mapillary vector tiles and I tailored a solution!

**Comment by CorentinLemaitre** [comment]
Hello, 

I did try the mapillary viewer on Lizmap but it didn't work. 

I did followed the process described in the readme (except the folder, i have put it in media/js/default as the button didn't show up if I put it in media/js).  I use chrome, I did get the button mapillary on the sidebar, the click that open and close a side box... but then it is grey. 

I have tried to update my token, to create a new one but it didn't change the result. My token format is `3letter|16number|32alphanumeric`.  I have use the client token on the mapillary website. 

Here is the screenshot of lizmap : 

image

Here is the console message on click on the icon : 

```
Uncaught TypeError: lizMap.mainLizmap.map.getLayers is not a function
    at Object.minidockopened (getMedia?repository=mobilite&project=SIG_V84&mtime=1661707961&path=media%2Fjs%2Fdefault%2Fmapillary.js:2:1337179)
    at initialize.triggerEvent (OpenLayers.js:255:145)
    at HTMLAnchorElement.<anonymous> (map.js:6330:27)
    at HTMLUListElement.dispatch (jquery-3.5.1.min.js:2:43090)
    at v.handle (jquery-3.5.1.min.js:2:41074)
```

**Comment by Gustry** [comment]
@CorentinLemaitre This PR has been closed in favor of #55. It's not clear which solution you used. Better to create a ticket and not commenting on a closed PR. Thanks

**Comment by nboisteault** [comment]
@CorentinLemaitre If your issue occurred in Lizmap 3.5, please open a ticket.

**Comment by CorentinLemaitre** [comment]
@nboisteault i have used it in lizmap 3.4, i will do it in 3.5.

@Gustry : sorry I was thinking it was better openning original issue. If I have still an issue in Lizmap 3.5 I will do a new ticket. :+1:

**Comment by nboisteault** [comment]
@CorentinLemaitre I found a bug. Mapillary script will work with coming Lizmap 3.5.6 version.
